<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run(): void
    {
        $users =  [
            [

                'name' => 'IT Department',
                'mobile_number' => '0000000000',
                'employee_id' => '0',
                'email' => 'itd@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$C5p20tnTVdBab9FyKxs6BenghIqzIqDMIrhhXGm/.rHFe9fAbXJfm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2019-09-13 19:21:30',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Managing Director',
                'mobile_number' => '9851083448',
                'employee_id' => '000000',
                'email' => 'md@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$ZPeomI4BMYlQLqMhpe0OIuqVuvGsMNYae.WfnKmzYm4vmDCIeQEJa',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2019-09-13 19:21:30',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Sangita Giri',
                'mobile_number' => '9860980011',
                'employee_id' => '189165',
                'email' => 'sangitagiri038@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$0gU9ZBxmlaISLqhkDfwVt.rv6rpsgGK5PoCfUeHQkMVIQ5Py4Zj5m',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:45:10',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Achyut Babu Ghimire',
                'mobile_number' => '9851024021',
                'employee_id' => '134897',
                'email' => 'ghiachyut@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$4SF8YZWss49VP6kY1JllS.uaVKlv.BXUNw/yKrTcSV6E9h2RZlseO',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-01 13:13:26',
                'updated_at' => '2025-09-01 13:13:26',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Amit Kumar Karna',
                'mobile_number' => '9841879582',
                'employee_id' => '139117',
                'email' => 'akkarna@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$aWbt.sueioRp38u5NuAHqeDU9ye.qJAcnyNvFVF/jW2W6lB0YH/MW',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:47:05',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Prabin Dhakal',
                'mobile_number' => '9851226811',
                'employee_id' => '131917',
                'email' => 'bsrep@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fG5TSSzGg7QKQcksVaqSV.l1UDuzoaa8vvW0hbrVp1kaBRrLgmip2',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:47:26',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Hari Prasad Pandey',
                'mobile_number' => '9857063272',
                'employee_id' => '179162',
                'email' => 'haripandey2009@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$HbJOtBtAxoUt8j/CL4/jjeAbXXb4CwR9ss8kaddwqePGADKbRHQXq',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:56:08',
                'updated_at' => '2025-09-16 11:28:59',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Khila Nath Aryal',
                'mobile_number' => '9852063354',
                'employee_id' => '156937',
                'email' => 'kmrsrep@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$BpwgQ.OXRw6RA5.l38dkBeYfiXSHtaz9Jx.aqE.hkhnGVj0oLG0i.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:50:08',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Ganesh Sah',
                'mobile_number' => '9851053326',
                'employee_id' => '148940',
                'email' => 'jiptep@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$d08nKL3yllrIxOVXBxavHe820REreAVabQl1lZD.EHdaDuck8MQM6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:50:49',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Anil Kumar Adhikari',
                'mobile_number' => '9851152005',
                'employee_id' => '176992',
                'email' => 'ddrep@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$IFNgtGtF7/l1yZfS8os5xuiEmRvWODlc2B.eG2SgCtpdHkbjRYCP6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:51:16',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Damodar Parajuli',
                'mobile_number' => '9841151918',
                'employee_id' => '158093',
                'email' => 'sorep@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$C.aHRJMmQffoRbid8p/lPuo25EB2wJ.tSrv4b55lit0cLnJh5LA9i',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:51:50',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Sandeep Shrestha',
                'mobile_number' => '9851002300',
                'employee_id' => '113628',
                'email' => 'smsg@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Qpd2bbeGSFD1HpCdKAxf.ureLCaUNkJhaAnE0si4Y6jNloKmfsEy2',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:52:57',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Suraj Bhuju',
                'mobile_number' => '9851153358',
                'employee_id' => '147659',
                'email' => 'ssrp@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$pqnEvjkZPx9f15f.prFUgOtPwtAoxUoAjFBKjPE7RPAmZXQ.6KKRq',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => 'uykMd5psEezQAO3hAmGm0orhQ7dUBBZMPmlkWyfhf75KLhqZPB5c6d8jTSaT',
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-10-12 09:41:56',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Badri Pyakurel',
                'mobile_number' => '9851136805',
                'employee_id' => '190799',
                'email' => 'kurep@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OrHIm3sfwZFnsz4SnYyIj.mV7IJbl8knOC/SeRDAv/G0hLYop0oku',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:53:55',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'DCS Anugaman',
                'mobile_number' => '0000111111',
                'employee_id' => '000011',
                'email' => 'dcsanugaman@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$4YtW5Ovt.etX0PhCmdEKzeHVarFtWxazs6sIBjrvbAgzv9WeQ6J3O',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:54:08',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Engineering Directorate',
                'mobile_number' => '9851130590',
                'employee_id' => '000009',
                'email' => 'engineering@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$vjs3zV68pR3pe3cphaX0Nu3YJAjy.vCcPKlV4B65KERr9vM2NHyEm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:54:32',
                'deleted_at' => NULL,
                'directorate_id' => 9,
            ],

            [

                'name' => 'PMD Directorate',
                'mobile_number' => '9851337068',
                'employee_id' => '000004',
                'email' => 'pmd@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fkvsmGVolOBODPNUI2BhVucN6K6Klwm/CwYJHL/RrzApA1dvpjJ/K',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:54:50',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Transmission Directorate',
                'mobile_number' => '9851181228',
                'employee_id' => '000002',
                'email' => 'transmission@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Olsz9d7OC/jq4dcX3B91oe2am4u3CejtaxOUGJB438dhmp1Z1tZAC',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:55:02',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'DCS DMD',
                'mobile_number' => '9841241316',
                'employee_id' => '000001',
                'email' => 'dcsdmd@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SAM3M.UhkqhrdH6i2mQT.OlNslAQ.ZEcUO5KMOa6Qreh55Xs7O4B6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:55:16',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Thark Bahadur Thapa',
                'mobile_number' => '9841224939',
                'employee_id' => '155777',
                'email' => 'hvgdd.nea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$v1sCnhfnzG60zKkuH.OzOutED5DKmcC6znExNHcSwK1GOoPzM/fM.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:56:52',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Ramu Shrestha',
                'mobile_number' => '9857028970',
                'employee_id' => '166126',
                'email' => 'ramushrestha@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SRysY1QeqGUIDFjy6iU95O1dbbzEapInb2ViN7ENPzkEaQucNn4vO',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:57:18',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'DIPESH SHRESTHA',
                'mobile_number' => '9851168810',
                'employee_id' => '121261',
                'email' => 'dipesh.nea81@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$FaLZBnxRbmdD.RyspKIUhOjPAVHuHqa/J.BVBdubw82Sn/zd3WYCm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:49:46',
                'updated_at' => '2025-09-02 07:11:27',
                'deleted_at' => '2025-09-02 07:11:27',
                'directorate_id' => 4,
            ],

            [

                'name' => 'Sushil Aryal',
                'mobile_number' => '9851180666',
                'employee_id' => '153530',
                'email' => 'sushilaryal@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$J8wIYvCZudEUdDbBr1L/hOrcL5wGuWF5P5PCwUtIVZ0Tmb3fzPdWm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:51:18',
                'updated_at' => '2025-09-02 05:20:21',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Bijay Sen Khadka',
                'mobile_number' => '9852042698',
                'employee_id' => '180505',
                'email' => 'dsuep.eib@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fxDhbwFW.QPd3V/eWwzzEOW7QzKx/GqBidkGCDhOL0oYB8VWz.7/e',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-08-29 04:59:07',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Amit Gopal Vaidya',
                'mobile_number' => '9841366737',
                'employee_id' => '128948',
                'email' => 'vaidyagopal@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ekn9GGL8OiZBRSm13tnIg.F9tFrbyKyuSXeQUycvxmgvN9N4RbPly',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-08-31 11:34:44',
                'updated_at' => '2025-08-31 11:36:50',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Rupesh Kumar Shah',
                'mobile_number' => '9841534089',
                'employee_id' => '158470',
                'email' => 'shah.rupeshkumaar@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DJqIInXibbfoAmEI5CM7hudNi1gMHzB8zChno4gJYqpWCpa.scruG',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-08-31 11:55:46',
                'updated_at' => '2025-08-31 11:57:54',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Ranjanraj Gurung',
                'mobile_number' => '9851155752',
                'employee_id' => '124641',
                'email' => 'ranjanraj.gurung@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$B5wgs7.cvJWvBhYc6DhNJeLGqZj1vvh4eRGcYUsWr1bsmXXXAaNMi',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-01 00:37:09',
                'updated_at' => '2025-09-01 00:37:09',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Ravi Shrestha',
                'mobile_number' => '9841006704',
                'employee_id' => '197654',
                'email' => 'ravi.nea78@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$xuvzAGw.PL/cny5bv.rCqe2.4c9OiBN2LG.mTs02wmNDwNjkzRx6y',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-01 00:40:16',
                'updated_at' => '2025-09-01 00:40:16',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Dhirendra Kumar Yadav',
                'mobile_number' => '9841453469',
                'employee_id' => '177599',
                'email' => 'dhirendra.yadav@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$jdsk.zZn0Klr02a/OAB/Pe/O7uBANAtbgxdQMDBOiUhiJscsLB/PS',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-09-01 04:50:01',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Shiva Ram Tamrakar',
                'mobile_number' => '9841780124',
                'employee_id' => '158796',
                'email' => 'cvaram.tamrakar@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$8DR71MlExdKK0K0DUh36g.clkl/DPN7R9nccDzUyOfx6DDVPvfrSO',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-01 05:47:43',
                'updated_at' => '2025-09-01 05:47:43',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Bhupesh Shrestha',
                'mobile_number' => '9851212002',
                'employee_id' => '147849',
                'email' => 'bhupesh.nea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$6rO42W3QjCqrsiVLSVH8YuVHCwAIG4Cio0sj1iPB/0g4rLCXkMp7K',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:34:19',
                'updated_at' => '2025-09-02 04:34:19',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Deepa Shrestha',
                'mobile_number' => '9841767781',
                'employee_id' => '115102',
                'email' => 'er.deeps.stha@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$xKOHCLKHjJg9o.tza7pPPeWTNSilONj2x.hxEFck74avdD5Gx5uLi',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:38:14',
                'updated_at' => '2025-09-02 04:38:14',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Balbhadra Adhikari',
                'mobile_number' => '9851186385',
                'employee_id' => '128225',
                'email' => 'adhikaribalbhadra9@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$FlvF7xCt/hRx3p9KL3Q/JuHNKUTc4AYwlZbOgkNCIFkBbRaUnRedu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:40:43',
                'updated_at' => '2025-09-02 04:40:43',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Narayan Sapkota',
                'mobile_number' => '9851234151',
                'employee_id' => '155790',
                'email' => 'sapkotanarayan151@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$ZF3H2O3YdQlTXFPmbFiXh.d0zD1M9Ng67hktvMf6JUy9O.MQPEo5u',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:43:27',
                'updated_at' => '2025-09-02 04:43:27',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Ameet Bhagat',
                'mobile_number' => '9852059044',
                'employee_id' => '112032',
                'email' => 'amitnepal2003@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Xaz4M63IuSs84uQ1OTmh4.ymgDL4VzP82blJFb/QtDXts9i8v0Yi.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:52:19',
                'updated_at' => '2025-09-02 04:52:19',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Bishnu Prasad Devkota',
                'mobile_number' => '9851320837',
                'employee_id' => '138467',
                'email' => 'enggbishnu@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$mh8XfXWEIXS0ZotVmIktjeNwgcKiZQa04IV25W9IUFf/X.YINOQH2',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:47:14',
                'updated_at' => '2025-09-02 04:52:42',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Darshanray Yadav',
                'mobile_number' => '9851073273',
                'employee_id' => '8191',
                'email' => 'darshanrayyadav@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$2vgohucB13Eg0b4jPz/t0.WxxACPOkbE68gxQedEOnQMAxQrFSDU6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 04:55:26',
                'updated_at' => '2025-09-02 04:55:26',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Kailash Pantha',
                'mobile_number' => '9851362089',
                'employee_id' => '123814',
                'email' => 'kailash.pantha@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$qfknZCgoyt4p3OQmfKQ4BuTeJxUIA5fi7qcydg4xjNcyz2dZPxbF6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:00:19',
                'updated_at' => '2025-09-02 05:00:19',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Bimal Raj Raut',
                'mobile_number' => '9851198343',
                'employee_id' => '188412',
                'email' => 'nmrep2023@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$jGOY0Bcc6iXnjSZpzBH.Y.3D09hj88CNX5KH9BcFYpQyQzfANOlsm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => 'vVQyyXg4kCaXaKF0zKJHAOciwm2ZWrbsTT5BWYnECVwnzowPCQjiAeRczrkA',
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-09-02 10:31:24',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'Rajan Dhungel',
                'mobile_number' => '9851202309',
                'employee_id' => '128324',
                'email' => 'rajdhungel73@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$6osbeKz3O.IdHguwP0Z02eFdfd55rwGsBHDa1446RewTYqNsPBzSu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-09-02 10:57:36',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Raghbendra Jha',
                'mobile_number' => '9849788334',
                'employee_id' => '124947',
                'email' => 'rkjha014.1@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$VIhc1zBeRhdQQvIp8Tw5KuTL8ZvvBIkcVgps1IgDTf6niV4OgEzoC',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:04:44',
                'updated_at' => '2025-09-02 05:04:44',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Anup Gautam',
                'mobile_number' => '9851202001',
                'employee_id' => '196359',
                'email' => 'gautam.anup070@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$oAWrQJKDlDl7stKRS3eWR.6B3w07pZVZ6u6HCJmuUgaOQO6Tjgqn.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-09-02 05:11:01',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Dhupendra Kumar Jha',
                'mobile_number' => '9855043932',
                'employee_id' => '180568',
                'email' => 'neacstlp@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$bcfR15wt9ByrU7RHqXzWxeZg4HleKVGTjkZOi2IgbVzY8MIXHLe1u',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:18:37',
                'updated_at' => '2025-09-02 05:18:37',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Rabindra Shrestha',
                'mobile_number' => '9851157428',
                'employee_id' => '141322',
                'email' => 'rbshrestha87@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$YjRjJ3sWMDSZoVK/Wh9hxOf/tzJadJNIgYgpCkVH1xuAokr0RUWoi',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:22:13',
                'updated_at' => '2025-09-02 05:22:13',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Sunil Kumar Mahato',
                'mobile_number' => '9851126316',
                'employee_id' => '180273',
                'email' => 'sunilkmahto131@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$pPF.UnV97waPyFwiUaUEzO6ZPuRrRt2eGr4jvrv.Uprwq6TG2JC8K',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:23:21',
                'updated_at' => '2025-09-02 05:23:21',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Roshan Agrawal',
                'mobile_number' => '9849484903',
                'employee_id' => '11887',
                'email' => 'roshan_agr@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$F.a/UN0KDRsORKYS8DdLoedTyc/fn7SMdQLcCXKxnnQQNvt8KFTNK',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:24:30',
                'updated_at' => '2025-09-02 05:24:30',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Rajendra Koirala',
                'mobile_number' => '9851149244',
                'employee_id' => '149002',
                'email' => 'rako2035@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$WrmLk7cc0P/5Nfst.B/6guXzBD6ugoTbLY4TrJ1wFxnAtqIsjvSt2',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:25:34',
                'updated_at' => '2025-09-02 05:25:34',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Shuvarambha Bikram Shah',
                'mobile_number' => '9858036666',
                'employee_id' => '113498',
                'email' => 'shubharambha33@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$syCfX6CsqbD4TKaR1VDqQOZ5NWkS3pW4ESOoPVp8vG1ZelE8cVsU.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:25:44',
                'updated_at' => '2025-09-02 05:25:44',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Bodhnath Neupane',
                'mobile_number' => '9851126700',
                'employee_id' => '181438',
                'email' => 'neupane09@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Y1BPO3bNhz0aKmbEFtkWLOhIZryxz7OtEuYb.mEDq4N9tzqGHIMAa',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:29:30',
                'updated_at' => '2025-09-02 05:29:30',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Ukesh Shrestha',
                'mobile_number' => '9841964431',
                'employee_id' => '136016',
                'email' => 'ukesh123@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$.o2kdLxrCSavlR10Bze6K.RcEugcPOUOt3PoC3H7.BTuxjmKw/HBS',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:32:14',
                'updated_at' => '2025-09-02 05:32:14',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Sajun K. Shrestha',
                'mobile_number' => '9851008612',
                'employee_id' => '134743',
                'email' => 'sajuns@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$.1m1nnkn19ujWNumiLEaweMmQSA86Twz06LbDL5.YEVtBfCIUxgn2',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:36:35',
                'updated_at' => '2025-09-02 05:36:35',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Shukra Devkota',
                'mobile_number' => '9851131011',
                'employee_id' => '115552',
                'email' => 'sukra.devkota@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SwMjSGY/D2zd6OJLvb33VekrBR4oDR9GcRqIhlhpwrh2u/NWM1x8O',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:43:31',
                'updated_at' => '2025-09-02 05:43:31',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Shishir Pokhrel',
                'mobile_number' => '9857011265',
                'employee_id' => '157589',
                'email' => 'dkj.nea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$siYp2/2266Kw7ZCCL.PUaOdFfglHUlpo9Tz2RDNzXJROT6yhP3yc2',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:44:37',
                'updated_at' => '2025-09-02 05:44:37',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Surendra Chaudhary',
                'mobile_number' => '9851134611',
                'employee_id' => '195528',
                'email' => 'surenchaudhary@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$.yrEa3eLEx24dh9kilOqK.tSEgc/L6X4Wllcdy.FticSQ9507F/U6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:48:33',
                'updated_at' => '2025-09-02 05:48:33',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Nabina Sanda',
                'mobile_number' => '9841605275',
                'employee_id' => '148854',
                'email' => 'nabina.sanda@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$wc.01gSloMtLEox8BWQoyuZw6q9PF6ri3iZriQMugJYtKWINqoiya',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:59:28',
                'updated_at' => '2025-09-02 05:59:28',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Brabim Manandhar',
                'mobile_number' => '9841491960',
                'employee_id' => '189749',
                'email' => 'brabim@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$K.tCDjTaGsZghqpOGf06vOsz907MxP/NovhlghmKsIowDbiq1QV6O',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:13:03',
                'updated_at' => '2025-09-02 06:13:03',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Nitish Paudel',
                'mobile_number' => '9851180398',
                'employee_id' => '117101',
                'email' => 'nitish.paudel@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$zkAR752uCmJecPoCQC1ZFuf9WV9bfrXoOPN6A7z0ll8z1d3qmRk/G',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:14:20',
                'updated_at' => '2025-09-02 06:14:20',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Abhaya Neupane',
                'mobile_number' => '9851313730',
                'employee_id' => '145486',
                'email' => 'abhayaneupane@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$jeSEN6FDOPYOrbUsI/WRc.hdKlqR4Ne7RA4zOojaKgvG0Vcv1a7EG',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:27:33',
                'updated_at' => '2025-09-02 06:27:33',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Sumit Shrestha',
                'mobile_number' => '9841534937',
                'employee_id' => '177222',
                'email' => 'sumitshre@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$2L9ydBlYeNuG1WnZiYtm2.BQqJyGnmSL9HY1o/soJpzMz0vodsP/C',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:29:10',
                'updated_at' => '2025-09-02 06:29:10',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Suman Shrestha',
                'mobile_number' => '9851181666',
                'employee_id' => '173466',
                'email' => 'sumanshtha@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$M0uxApZU/Jy1jvkF0yYkS.vZMn4ywbD6iXd.YTPGrFHQ2BqGD8Kxy',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:30:00',
                'updated_at' => '2025-09-02 06:30:00',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Randhir Pathak',
                'mobile_number' => '9854033377',
                'employee_id' => '140203',
                'email' => 'randhirpathak.854@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OtYJDcqBLIJOyCLao5RXxunqwkDVfCIa9sI4pxh3k9xORfYh5I06K',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:32:55',
                'updated_at' => '2025-09-02 06:32:55',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Prakash Paudel',
                'mobile_number' => '9841955746',
                'employee_id' => '139448',
                'email' => 'prakash311@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Gqi3vPWi8pRnuFh5pInY3e0t.R3qpR1XVp5MKL.fGQz/fFkOc7rWy',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:34:30',
                'updated_at' => '2025-09-02 06:34:30',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Yogendra Thakur',
                'mobile_number' => '9851122244',
                'employee_id' => '8065',
                'email' => 'ythakur@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$qLGZ0EtqyMCDdlvnfx284.g3xKL.PbE7LhNHue84QRB9qYvgV5TdG',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:35:06',
                'updated_at' => '2025-09-02 06:35:06',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Piyush Malakar',
                'mobile_number' => '9841285312',
                'employee_id' => '163922',
                'email' => 'piyushmalakar@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fxt.kLa0UfMalv.h.rfXee3T9/ptxSU/6N5DA0LjvQMvSNOF90CB.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:36:21',
                'updated_at' => '2025-09-02 06:36:21',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Sagar Gyawali',
                'mobile_number' => '9851140230',
                'employee_id' => '182667',
                'email' => 'sagar@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DNiWR.TYg9rYAtR1uFqJrevFEv9dX.D/0B9YPpNH3kS8q4ppTP8ue',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:37:17',
                'updated_at' => '2025-09-02 06:37:17',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Bikram Poudel',
                'mobile_number' => '9851224569',
                'employee_id' => '184756',
                'email' => 'paudelbikram08@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$USalgXK8KeIMuhvxlUcHOexQMGvkd/irlKG59plNWwzgKngApQ8Gu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:38:05',
                'updated_at' => '2025-09-02 06:38:05',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Narayan Regmi',
                'mobile_number' => '9851147454',
                'employee_id' => '142824',
                'email' => 'mc220kv@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$KzV9iQ5IF.blnDN1h9N0Me5MPNDfljBSv5abxLdbi0pazxg0UHUfu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:39:31',
                'updated_at' => '2025-09-02 06:39:31',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Laxman Phuyal',
                'mobile_number' => '9841338201',
                'employee_id' => '141758',
                'email' => 'laxmanmkproject@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$c93kOV5BMzCiYA6NMHJHpOw2uZDskLo4TCl5ox0mN1F/IUhRLo3kG',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:40:52',
                'updated_at' => '2025-09-02 06:40:52',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Saroj Shrestha',
                'mobile_number' => '9851202525',
                'employee_id' => '149608',
                'email' => 'nea.saroj@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$vslEyc8TGo4n8eoXA0ASlOVZ2zQdXhASUxeLSGqeehpMOZTDATTtm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:45:06',
                'updated_at' => '2025-09-02 06:45:06',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Manoj Aryal',
                'mobile_number' => NULL,
                'employee_id' => NULL,
                'email' => 'manojaryal87@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$zsnEllJB0GsHBOtXyq/EhuzwR7BKuLMQ7ZHvASBVW0Sn0qxSGM8BO',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:57:53',
                'updated_at' => '2025-09-02 06:57:53',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Kapil Mishra',
                'mobile_number' => '9841128093',
                'employee_id' => '143442',
                'email' => 'nea42.kapil@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$qNVD3vgfbWwHb62pdR0WHuQPikT/pYG9U25c7JX94ApDZgs0bAoPe',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 07:13:17',
                'updated_at' => '2025-09-02 07:13:17',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Pankaj Kumar Singh',
                'mobile_number' => '9844221550',
                'employee_id' => '173473',
                'email' => 'singhpankajnea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$e6OZy3b1AwwwaFo03f42juyQCw/C3LYAg8QNrhTy7QHGzj.Bry4Ci',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 07:15:04',
                'updated_at' => '2025-09-02 07:15:04',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Sadam Bala',
                'mobile_number' => '9841117419',
                'employee_id' => '12345',
                'email' => 'sumitbala0@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$hAGDvCVZJtv5aZ1YCKcLIOpzy.UlEB1wRJJJNvDkJy.kGbpKd7Q3.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 07:28:18',
                'updated_at' => '2025-09-02 07:28:18',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Birendra Kumar Jha',
                'mobile_number' => '9851122932',
                'employee_id' => '124253',
                'email' => 'bkjha701@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$xRh6KMXYf/EkuKhYZwojaOADtugARGuaRsprIV34p1vraKuR9Ukja',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:46:46',
                'updated_at' => '2025-09-02 07:36:51',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Satish Chandra Sah',
                'mobile_number' => '9841273504',
                'employee_id' => '112995',
                'email' => 'sahsatishchandra@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$ZOCiO2nJzeZBJOYulh2l..eaC5ZR35MEZRE71Pd/zT7MO4ob667Ga',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 07:37:26',
                'updated_at' => '2025-09-02 07:37:26',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Jagdish Sharma Poudel',
                'mobile_number' => '9846025470',
                'employee_id' => '192484',
                'email' => 'ld220kvtlp@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fHV4reZ/lKkxg1DPcAN46u5OoH8.qOuj02HF4r1o7eSA4iwOhDXpu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 07:40:57',
                'updated_at' => '2025-09-02 07:40:57',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Puskar Deo',
                'mobile_number' => '9841494201',
                'employee_id' => '124413',
                'email' => 'pushkar.130@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SjZxtNoo85h/1McSl/YilOm1gQFFTkgjUGHDmsbCnjkW.MD5JpYD6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 07:43:27',
                'updated_at' => '2025-09-02 07:43:27',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Ravi Kumar Chaudhary',
                'mobile_number' => '9841378909',
                'employee_id' => '146957',
                'email' => 'eravinea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$.RaWLtGtpk/mH60fWnoeK.E/pa94Hbx8ghifZWEXoCK.w6WGCZHU2',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 07:49:57',
                'updated_at' => '2025-09-02 07:49:57',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Aananda Subedi',
                'mobile_number' => '9841974455',
                'employee_id' => '153429',
                'email' => 'aananda.nea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$AVqCcRC3kWSRA5oVnK0Aie9bSfTyBvUnJOC8A5Ju3F/NcNd.p9FWW',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:35:49',
                'updated_at' => '2025-09-02 13:07:09',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Vishwa Ranjan Mishra',
                'mobile_number' => '9851140623',
                'employee_id' => '187748',
                'email' => 'vishwa.nea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Bqcz4Rg7Xo8WsS8Lu8PnyO9wp81QHobqo9xxP5XWB3zTQA6bVzFKa',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:12:06',
                'updated_at' => '2025-09-03 04:24:21',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Amaresh K Jha',
                'mobile_number' => '9841244084',
                'employee_id' => '183656',
                'email' => 'rmsnea9@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$LvLtrv.b1LPfopsYAZ6aqOmlTeHpRBHHyCpk5xaPbDAj481ehZsgu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 05:35:02',
                'updated_at' => '2025-09-03 04:49:17',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'DIPESH SHRESTHA',
                'mobile_number' => '9841068810',
                'employee_id' => '170213',
                'email' => 'dipesh.shrestha@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1e3wh3r4Xh8qwFODrqtbsuYZmvpiMrTiQWpjbIESw38zvTDIuAtSC',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 08:53:15',
                'updated_at' => '2025-09-02 08:53:15',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Bissam Binod Khanal',
                'mobile_number' => '9846278277',
                'employee_id' => '188087',
                'email' => 'khanal.bisam@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$VLZAEqhq6RMiRd/N0wc1AeLeeOZaJhBn/NatSbDfoIGFRIFFHkT8.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 09:23:52',
                'updated_at' => '2025-09-02 09:23:52',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Binod Manandhar',
                'mobile_number' => '9841133819',
                'employee_id' => '145648',
                'email' => 'mr.binod.manandhar@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$6bZwZJCfYHIswmHhMs6nfeMCikHpAvHh5ZhD5xaG5bKRgqcoIcYQq',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 09:37:37',
                'updated_at' => '2025-09-02 09:37:37',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Rajendra Prasad Joshi',
                'mobile_number' => '9841016702',
                'employee_id' => '187040',
                'email' => '016702@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$r2o1yKTe8GuxDj48zKqNFe.RmYQsSRkWp6azesWC.bf.XcrP10mny',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 09:49:39',
                'updated_at' => '2025-09-02 09:50:53',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Bimal Raj Raut',
                'mobile_number' => '9849351080',
                'employee_id' => '170186',
                'email' => 'krep2025@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$w/kvWusl7Ts0NWb1.vrhfuERTtQYk47jx7fKpSsSQm.a94lpAYmei',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 09:18:03',
                'updated_at' => '2025-09-02 10:29:58',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Abhishek Adhikary',
                'mobile_number' => '9841324391',
                'employee_id' => '165008',
                'email' => 'nea.abhishek@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$zayeiA9..dyXm/gvLrwNwu5e5AD43neOWDd..wbwEOw.VGh0WqTP6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 06:28:27',
                'updated_at' => '2025-09-02 10:39:47',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Dhupendra Jha',
                'mobile_number' => '9851155046',
                'employee_id' => '18056',
                'email' => 'dhupendra@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$5e/ZWAG7AlyZQ.7FtMACX..kBeaqIjDwyXEvXmBacXLNfhfa/5UYq',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 10:58:08',
                'updated_at' => '2025-09-02 11:00:02',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Rajan Dhungel',
                'mobile_number' => '9851202300',
                'employee_id' => '11898',
                'email' => 'pangtansubstation@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$tncaj0EbAOArzWVh4XVRZOYYUMqEJRLe0DaOC0u3LGgdZbFNGBLcm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 10:51:46',
                'updated_at' => '2025-09-02 11:11:27',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Ramesh Prasad Poudel',
                'mobile_number' => '0123456789',
                'employee_id' => '8017',
                'email' => 'pm.bnrtlp24@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$pP/mEYRrqbyKUapAt1DOTOluhJ.uwJ82MJh20/9UDLgVEFI5ZONRa',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 11:12:38',
                'updated_at' => '2025-09-02 11:13:44',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Mekhraj Joshi',
                'mobile_number' => '9849161102',
                'employee_id' => '158621',
                'email' => 'mekh0095@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$MA9.WYoWLFR6mc3SIvUDfOl6bJ1Uyk9P4AO8pyM/Cb1bYNJT1Ndz2',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 13:08:19',
                'updated_at' => '2025-09-02 13:08:19',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Ganesh Kumar Sah',
                'mobile_number' => '9843751846',
                'employee_id' => '1',
                'email' => 'neaganeshkumar@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$VoA.nXLg.yn3nOcqotTpg.GSnDyZkeM7MTVH09Ahbi5DWzZznv77G',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 14:10:00',
                'updated_at' => '2025-09-02 14:10:00',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Umesh Dahal',
                'mobile_number' => '9851179684',
                'employee_id' => '2',
                'email' => 'mailumdl@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$QQt1krU.dB6TIKKPiq4FC.khNuRQA3wtOQWreJB4.I3XrJd9vQRNi',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 14:13:47',
                'updated_at' => '2025-09-02 14:13:47',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'MD Secretriat',
                'mobile_number' => '9851219678',
                'employee_id' => '999999',
                'email' => 'mdsecretriat@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Cd/nSQkT7nii9tPjLdGx8uusmbGcjHIPK3o.Y8mYLL0P1HSmm5.Zu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 06:53:36',
                'updated_at' => '2025-09-03 06:53:36',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Dhirendra Bajgain',
                'mobile_number' => '9841182513',
                'employee_id' => '197442',
                'email' => 'buzzgain.dhiren7@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$2/glPT1Vy3RXqbWNjyjcLOl8JQ2ugyv/iUOop1CdVC5A9lF9qVX8K',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 09:26:52',
                'updated_at' => '2025-09-03 09:26:52',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Sailendra Tamang',
                'mobile_number' => '9842049361',
                'employee_id' => '142234',
                'email' => 'sailesstamang@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$GDe0soLr0vkYNNOg3JE7aenYaMKY1dHWVKI9GNUWEak7oplROkv/y',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 09:28:04',
                'updated_at' => '2025-09-03 09:28:04',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Laxmi Gautam',
                'mobile_number' => '9841537068',
                'employee_id' => '234321',
                'email' => 'gautamlaxmig@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$5hnkFChBuCCAlHNXyH0Hu.lwuawfBgYsjnYDOk1xPt5xY5cd8eewe',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 09:32:05',
                'updated_at' => '2025-09-03 09:32:05',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Shakti Sah',
                'mobile_number' => '9804848481',
                'employee_id' => '197337',
                'email' => 'shaktisah22@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$CS2ZiJyKX/9QeAnnmtuEDOM/.IHwemKBBvEHT0UROqsKi0Zl9tfo.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 09:23:49',
                'updated_at' => '2025-09-03 09:47:58',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'TikaDahal',
                'mobile_number' => '9841423969',
                'employee_id' => '121221',
                'email' => 'tkadahal@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$9NgLxaIyHotK5Gxph9ZKt.cnuWatAV9JUZ9uXAgXVB3Wy3u/SyJAe',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 09:50:58',
                'updated_at' => '2025-09-03 09:50:58',
                'deleted_at' => NULL,
                'directorate_id' => 5,
            ],

            [

                'name' => 'Balbhadra Adhikari',
                'mobile_number' => '9864059860',
                'employee_id' => '12822',
                'email' => 'gm132kvtlp@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$18VkXu2kBGppgr/KqOfqpO4H6hACIews9HL8ZxyiG5HEH/EKDLv8e',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 10:26:13',
                'updated_at' => '2025-09-03 10:26:13',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Ibaraj Niraula',
                'mobile_number' => '9851106533',
                'employee_id' => '137056',
                'email' => 'ibarajniraulas@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$oy7tbP8g3ODNOL7nOVhFoOeQIKRD5n.j8a60biTyua1Zop6C2coXi',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 10:34:13',
                'updated_at' => '2025-09-03 10:34:13',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Ranjan Raj Gurung',
                'mobile_number' => '9851155750',
                'employee_id' => '144641',
                'email' => '132kvsp@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$xtBnngP/BvxMT0H.UGXgHOPck8Ya541hQ7JPhT6z4UHV7b0KQtqFK',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 11:18:29',
                'updated_at' => '2025-09-03 11:18:29',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'prabin dhakal',
                'mobile_number' => NULL,
                'employee_id' => NULL,
                'email' => 'prbndhkl@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SKz4Xs7eaUrdrr7TlntvceJ1YpBfHIgD7eEYxQnsN6qRFe1jJQZw.',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 11:36:05',
                'updated_at' => '2025-09-03 11:36:05',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'HDI 400KV HI',
                'mobile_number' => NULL,
                'employee_id' => NULL,
                'email' => 'hdi400kvep1@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$7B0Ie75TfJKaazVCK3faxuMygnVMQG0cEgcnDKGWKl.tGsfaOngOa',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-04 09:12:28',
                'updated_at' => '2025-09-04 09:12:28',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Arjun Ghimire',
                'mobile_number' => '9849543034',
                'employee_id' => '182438',
                'email' => 'ghimire.arj@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$bc9gKPyAGtIdYenyx89WL.UZIWNX4EQ8eb4X6/RCmBU7YKxh3uPsi',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-04 10:00:32',
                'updated_at' => '2025-09-04 10:00:32',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Prabhat Karki',
                'mobile_number' => '9849755647',
                'employee_id' => '155399',
                'email' => 'karkiprabhat2050@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DKccZ4pjagtO2RorXBbXwu5XEAL8N.rYGbbkLauMjJbGmoLbgjAfm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-04 10:09:29',
                'updated_at' => '2025-09-04 10:09:29',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Saroj Twanabasu',
                'mobile_number' => '9851216660',
                'employee_id' => '153310',
                'email' => 'twanabasu.saroj@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$rZKVcITeYNzx0F0eJLeUweMP2qzGb80WS.rhpqMV6ghHHPWB.H/3S',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-02 08:39:52',
                'updated_at' => '2025-09-04 10:53:22',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Narayan Aryal',
                'mobile_number' => '9851126275',
                'employee_id' => '176035',
                'email' => 'narayanaryalnea124@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Sa9vjN//zr6hJnFqkTsJneCI1T3kkEmupO8Jpo37R7ohrCY0T/obS',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-03 07:43:45',
                'updated_at' => '2025-09-05 08:34:51',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Janardan Gautam',
                'mobile_number' => '9841453902',
                'employee_id' => '129536',
                'email' => 'janardangautan@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$xb1qMfELPKgdpsGzNju.Bu7wlncy7WxLfYc3oB5MFza1vGpeqcgte',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-16 11:11:36',
                'updated_at' => '2025-09-16 11:13:31',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Parmardhir Sen',
                'mobile_number' => '9851191188',
                'employee_id' => '113216',
                'email' => 'dhirsen@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$wGjB0HPxHnUzuoBDutf6C./AOXPRFqRh/DDDkq2DAFpglicsGbgsm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-16 11:17:01',
                'updated_at' => '2025-09-16 11:17:01',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Ramesh Prasad Poudel',
                'mobile_number' => '9851157176',
                'employee_id' => '189952',
                'email' => 'poudelrameshnea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$7VTYITYCMX/5qNdQogAfIeJczGUzOkFdPh3Msn/0pd4CT34dR7Kzy',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-09-16 11:26:03',
                'updated_at' => '2025-09-16 11:26:24',
                'deleted_at' => NULL,
                'directorate_id' => 2,
            ],

            [

                'name' => 'Khimti Lapsiphedi',
                'mobile_number' => NULL,
                'employee_id' => NULL,
                'email' => 'kbl400kv@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$RvQ1c.OnOyI6yC8s.NLIFOPY77t/vQKkhIbCC0xPGDwQDAM6Rb55q',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-05 10:01:03',
                'updated_at' => '2025-11-05 10:01:03',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Subash Dahal',
                'mobile_number' => '9860136012',
                'employee_id' => '170129',
                'email' => 'subash.dahal@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$HBW28q4ZKZDVABqEcNE7hONrlwLbHBR8uOkysIBDTCjeFksqRYrvy',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-10-09 06:20:36',
                'updated_at' => '2025-11-12 06:45:48',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],

            [

                'name' => 'SANJAY LOHANI',
                'mobile_number' => '9852828444',
                'employee_id' => '139745',
                'email' => 'lohani.sk44@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$M8wIUwQHryUwfFq6PJ6/YOCihRp3buYIkNjMdtWSScuxSV6RB9Ef6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-05 10:07:26',
                'updated_at' => '2025-11-05 10:07:26',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'KVTCRP, PTDEEP, PMD, NEA',
                'mobile_number' => NULL,
                'employee_id' => NULL,
                'email' => 'kvtcrp1@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$eUHp1FSuQrv0Tl5DdDsNb.H5fxCwrlvbVT0RrsWWwzL5Fcd8JQOiu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-06 05:19:56',
                'updated_at' => '2025-11-06 05:19:56',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Bijay Shrestha',
                'mobile_number' => '9841245607',
                'employee_id' => '123028',
                'email' => 'kvsmp2@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$BoTPRpOr.Zm75USGCVAsZOG0eu5dPu2za.b/V6PcqbDtFroUsbmni',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => '4tDvplyBaeBhQagyAJYyIrSaIufyYEMufk9l8WpjCSvt1ugJQxNUN1KnMYMw',
                'created_at' => '2025-09-02 05:41:55',
                'updated_at' => '2025-10-13 09:09:53',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Aman Rajbhandari',
                'mobile_number' => '9851193501',
                'employee_id' => '157390',
                'email' => 'rajbhandari.aman@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$njMI0z8Pz/5812N5r0l61uklVeQYncamnqbQvwBb0KToqPAecPRPa',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-10-08 12:02:09',
                'updated_at' => '2025-11-06 05:35:20',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Prakash Parajuli',
                'mobile_number' => NULL,
                'employee_id' => NULL,
                'email' => 'eee.prakash.parajuli@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$.E8KmM6URszefVtaPaib3eXJIU9vX31LbqxfHNYcJ2QzEYXc0Kzpy',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-06 08:01:23',
                'updated_at' => '2025-11-06 08:01:23',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Niranjan Adhikari',
                'mobile_number' => NULL,
                'employee_id' => NULL,
                'email' => 'ce.adniranjan@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$368Uia.VIO1dl31gtu8vh.FJj5tgW1Rkb2WUqc28p/KZFEtXlcmuC',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-06 08:12:59',
                'updated_at' => '2025-11-06 08:12:59',
                'deleted_at' => NULL,
                'directorate_id' => NULL,
            ],

            [

                'name' => 'Prakash Parajuli',
                'mobile_number' => '9843722095',
                'employee_id' => '170263',
                'email' => 'prakash.parajuli@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$JoVll5BtbWNZgF9x6vZ8KuCRmSZ199bTiXv./M16c2eL5vQ7zBYIW',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-06 08:27:51',
                'updated_at' => '2025-11-06 08:27:51',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Niranjan Adhikari',
                'mobile_number' => '9849754065',
                'employee_id' => '175891',
                'email' => 'niranjan.adhikari@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$nVqjmgLRA35veB6bH1ywoeqiK6jIFDxpIL2V/43n3RgA6WeWqG0Tu',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-06 08:58:53',
                'updated_at' => '2025-11-06 08:58:53',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Arjun Ghimire',
                'mobile_number' => '9810078820',
                'employee_id' => '170460',
                'email' => 'ghimire.arj1@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$z07CNcZFoIA7NulpCgapE.7PETDFJYmZNbzhrv6FJnAujXM.aBh96',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-07 06:58:11',
                'updated_at' => '2025-11-07 06:58:11',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Gorakh Prasad Timalsina',
                'mobile_number' => '9845399620',
                'employee_id' => '133717',
                'email' => 'gptgokul20@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$H.j0Z7sMfNX3S3nKgueEgOReIgBmZDN5aprbrCClfNMNBpda9Purm',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-07 06:59:27',
                'updated_at' => '2025-11-07 06:59:27',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Dilip Kumar Bhatta',
                'mobile_number' => '9860144885',
                'employee_id' => '3909',
                'email' => 'bhattadilipnea@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$C3skKdZpO8gZ9No5kkEchOtWwCG3hOAle0CFqnA8w7VWWLE7ZrS/6',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-11-07 07:00:41',
                'updated_at' => '2025-11-07 07:00:41',
                'deleted_at' => NULL,
                'directorate_id' => 4,
            ],

            [

                'name' => 'Prakash Raut',
                'mobile_number' => '9851165102',
                'employee_id' => '191761',
                'email' => 'kfwproject@nea.org.np',
                'email_verified_at' => NULL,
                'password' => '$2y$12$5VoRcLo4Vgaoq56C/fnxj.vF8gAo21cP/v9fWq8STkHGF592yRS12',
                'last_login_at' => NULL,
                'last_login_ip' => NULL,
                'remember_token' => 'LqqdysWPo6CqAUQc1kyimd5vqdtlXcETEceBsppvn81owh8KbPbyPo3om28O',
                'created_at' => '2019-09-13 19:21:30',
                'updated_at' => '2025-10-10 07:15:53',
                'deleted_at' => NULL,
                'directorate_id' => 1,
            ],
        ];

        User::insert($users);
    }
}
